### ISSUE TITLE
Feature: set Bounding Box information to tabular to be able to search via geolocation in the repo

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/contrib_datapackage#19]
## Feature Description

currently all uploaded tabular datasets have a fixed bounding box like 0,0,0,0. If you add a tabular dataset to a map together with a geo dataset the bounding box of the map gets extended to 0,0,0,0. As this is not what we want tabular data must be ignored when be added to a map.

**Comment by mwallschlaeger** [comment]
i'm going to close this as it is part of geonode. I opened an issue for this in zalf geonode.@ridoo IDK if we want to keep this changes in the usergroup geonode branch?
@

**Comment by ridoo** [comment]
@mwallschlaeger feel free to link the issue once created.
